# Generated by Django 2.1.2 on 2018-10-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentice_learner', '0006_auto_20171002_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(default='Legacy', max_length=50),
            preserve_default=False,
        ),
    ]
