image: "python:3.7"

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - lint
  - document
  - test
  - deploy

flake8:
  stage: lint
  allow_failure: true
  script:
    - pip install flake8 flake8-junit-report
    - retval=0
    - flake8 --output-file flake8.txt apprentice/ || retval=$?
    - flake8_junit flake8.txt flake8_junit.xml
    - cat flake8.txt
    - exit "$retval"
  artifacts:
    when: always
    reports:
      junit: flake8_junit.xml
  tags:
    - base

coverage:
  stage: document
  allow_failure: true
  script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - retval=0
    - coverage run --source apprentice -m pytest || retval=$?
    - coverage html -d coverage
    - coverage report
      # - exit "$retval"
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - coverage
  tags:
    - base

sphinx:
  stage: document
  allow_failure: true
  dependencies:
    - flake8
  script:
    - pip install -r requirements.txt
    - pip install -r docs/doc-requirements.txt
    - apt-get update
    - apt-get install make
    - cd docs
    - make html
    - mv _build/html/ ../sphinx
  artifacts:
    paths:
      - sphinx
  tags:
    - base
  only:
    - master

pytest:
  stage: test
  allow_failure: false
  script:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
      #- pip install tox
      #- tox
    - python -m pytest
  artifacts:
    when: always
    reports:
      junit: output.xml
  tags:
    - base


publish:
  stage: deploy
  dependencies:
    - sphinx
    - coverage
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git remote add public git@github.com:apprenticelearner/AL_Core.git
    - git push public master:soartech-dev
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - sphinx
    - coverage
  script:
    - mv sphinx public/
    - mv coverage public/coverage
  environment:
    name: pages
    url: https://hq-git.soartech.com/apprentice/apprentice
  artifacts:
    paths:
      - public
  tags: 
    - base
  only:
    - master

pypi:
  stage: deploy
  dependencies:
    - coverage
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://nexus.soartech.com:8443/nexus/repository/pypi-internal/ dist/*
  tags:
    - base
  only:
    - master
