version: '3'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
  apprentice:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - APPRENTICE_DB=postgres
